//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostingInIIS.OccuranceService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OccuranceService.IOccuranceCounting")]
    public interface IOccuranceCounting {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOccuranceCounting/Occurances", ReplyAction="http://tempuri.org/IOccuranceCounting/OccurancesResponse")]
        int Occurances(string searchTerm, string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOccuranceCounting/GetPerson", ReplyAction="http://tempuri.org/IOccuranceCounting/GetPersonResponse")]
        WordOccurance.Person GetPerson();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOccuranceCountingChannel : HostingInIIS.OccuranceService.IOccuranceCounting, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OccuranceCountingClient : System.ServiceModel.ClientBase<HostingInIIS.OccuranceService.IOccuranceCounting>, HostingInIIS.OccuranceService.IOccuranceCounting {
        
        public OccuranceCountingClient() {
        }
        
        public OccuranceCountingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OccuranceCountingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OccuranceCountingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OccuranceCountingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Occurances(string searchTerm, string text) {
            return base.Channel.Occurances(searchTerm, text);
        }
        
        public WordOccurance.Person GetPerson() {
            return base.Channel.GetPerson();
        }
    }
}
