//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordOccurance
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/WordOccurance")]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AgeField;
        
        private int IdField;
        
        private bool IsProgrammerField;
        
        private decimal MoneyField;
        
        private string NameField;
        
        private string[] SertificatesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age
        {
            get
            {
                return this.AgeField;
            }
            set
            {
                this.AgeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsProgrammer
        {
            get
            {
                return this.IsProgrammerField;
            }
            set
            {
                this.IsProgrammerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Money
        {
            get
            {
                return this.MoneyField;
            }
            set
            {
                this.MoneyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Sertificates
        {
            get
            {
                return this.SertificatesField;
            }
            set
            {
                this.SertificatesField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IOccuranceCounting")]
public interface IOccuranceCounting
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOccuranceCounting/Occurances", ReplyAction="http://tempuri.org/IOccuranceCounting/OccurancesResponse")]
    int Occurances(string searchTerm, string text);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOccuranceCounting/Occurances", ReplyAction="http://tempuri.org/IOccuranceCounting/OccurancesResponse")]
    System.Threading.Tasks.Task<int> OccurancesAsync(string searchTerm, string text);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOccuranceCounting/GetPerson", ReplyAction="http://tempuri.org/IOccuranceCounting/GetPersonResponse")]
    WordOccurance.Person GetPerson();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOccuranceCounting/GetPerson", ReplyAction="http://tempuri.org/IOccuranceCounting/GetPersonResponse")]
    System.Threading.Tasks.Task<WordOccurance.Person> GetPersonAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IOccuranceCountingChannel : IOccuranceCounting, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class OccuranceCountingClient : System.ServiceModel.ClientBase<IOccuranceCounting>, IOccuranceCounting
{
    
    public OccuranceCountingClient()
    {
    }
    
    public OccuranceCountingClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public OccuranceCountingClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public OccuranceCountingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public OccuranceCountingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int Occurances(string searchTerm, string text)
    {
        return base.Channel.Occurances(searchTerm, text);
    }
    
    public System.Threading.Tasks.Task<int> OccurancesAsync(string searchTerm, string text)
    {
        return base.Channel.OccurancesAsync(searchTerm, text);
    }
    
    public WordOccurance.Person GetPerson()
    {
        return base.Channel.GetPerson();
    }
    
    public System.Threading.Tasks.Task<WordOccurance.Person> GetPersonAsync()
    {
        return base.Channel.GetPersonAsync();
    }
}
